---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    type: redis
spec:
  replicas: 2
  selector:
    matchLables:
     type: redis
  template:
    metadata:
      name: redis-pod
      labels:
        type: redis
    spec:
      containers:
        - name: redis
          image: redis