---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deployment
  labels:
    type: worker-app
spec:
  replicas: 2
  selector:
    matchLabels:
      type: worker-app
  template:
    metadata:
      name: worker-app-pod
      labels:
        type: worker-app
    spec:
      containers:
       - name: worker-app
         image: dockersamples/examplevotingapp_worker